config/routes.rb
Rails.application.routes.draw do

  root 'site#index'


  get '/cards/:id/send', to: 'cards#sendmail', as: 'sendmail'
  post '/cards/:id/send', to: 'cards#email', as:'email'
  get '/cards/:id/preview', to: 'cards#emailpreview', as: 'emailpreview'

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users do
    resources :cards, shallow: true
  end
  
end

#       root GET    /                                   site#index
#    user_cards GET    /users/:user_id/cards(.:format)     cards#index
#               POST   /users/:user_id/cards(.:format)     cards#create
# new_user_card GET    /users/:user_id/cards/new(.:format) cards#new
#     edit_card GET    /cards/:id/edit(.:format)           cards#edit
#          card GET    /cards/:id(.:format)                cards#show
#               PATCH  /cards/:id(.:format)                cards#update
#               PUT    /cards/:id(.:format)                cards#update
#               DELETE /cards/:id(.:format)                cards#destroy
#         users GET    /users(.:format)                    users#index
#               POST   /users(.:format)                    users#create
#      new_user GET    /users/new(.:format)                users#new
#     edit_user GET    /users/:id/edit(.:format)           users#edit
#          user GET    /users/:id(.:format)                users#show
#               PATCH  /users/:id(.:format)                users#update
#               PUT    /users/:id(.:format)                users#update
#               DELETE /users/:id(.:format)                users#destroy

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :usercards, dependent: :destroy
  has_many :users, through: :usercards
  validates :image_url, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :usercards, dependent: :destroy
  has_many :cards, through: :usercards
  # validates :name, presence: true


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth (auth)
    create! do |user|
      user = User.new
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.first_name = auth["info"]["first_name"]
      user.last_name = auth["info"]["last_name"]
      user.email = auth["info"]["email"]
    end
  end
end

app/models/usercard.rb
class Usercard < ActiveRecord::Base
  belongs_to :user 
  belongs_to :card

  validates :user_id, uniqueness: {scope: :card_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
def require_user
  redirect_to root_path unless current_user
end

  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # rescue ActiveRecord::RecordNotFound
  end
  
  helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :current_user 

  require 'mandrill'
  # mandrill = Mandrill::API.new ENV["MANDRILL_APIKEY"]

  before_action :find_user_id, only: [:create, :destroy]
  def index
  end

  def new
    @templateCard = Card.find_by_id(params[:template])
    @card = Card.new

    if @templateCard
     @card.image_url = @templateCard.image_url
    end
  end

  def create
    @card = Card.new(card_params)
    @card.users << @user
    # @card.update(image_url: params[:image_url])
    
    if @card.save
      puts "card saved"
      redirect_to @card
    else
      puts "card not saved"
      redirect_to new_user_card_path(@user)
    end 

  end

  def show
    # @templateCard = Card.find_by_id(params[:template])
    @card = Card.find(params[:id])
    # @user = User.find(params[:user_id])
  end

  def emailpreview
    @card = Card.find(params[:id])
    render :emailpreview
  end

  def sendmail
    @card = Card.find(params[:id])
    render :sendmail
  end

  def email
    @card = Card.find(params[:id])
    # require 'mandrill'  
    # m = Mandrill::API.new
    m = Mandrill::API.new ENV["MANDRILL_APIKEY"]
    send_to_email = params[:email]
    # card_id = @card.id
    # m = Mandrill::API.new
   #  message = {
   #  :subject=> "You got an E_card!",
   # :from_name=> "E_card_Designs",
   # :to=> [email:"aparna.sainath@gmail.com"],
   # :html=>"<html><h1>ssfdfdf</h1></html>",
   #  }

  message = {  
   :subject=> "You got an e-card!",  
   :from_name=> "E_card_Designs",
   :text=>"Hi message, how are you?",  
   :to=>[  
     {  
       :email=> send_to_email,  
       :name=> "Recipient1"  
     }  
   ],  
   :html=>"<html>Your ecard!<a href='https://strawberry-pudding-8666.herokuapp.com/cards/#{@card.id}/preview'>click here</a></html>", 
   

#{params[:send_to]}
   :from_email=>"test@test.com"  
  }  
  sending = m.messages.send message
  puts sending

flash[:alert] =  "Message Sent!"
redirect_to user_path(@current_user)

  end

  def edit
  end

  private 
  def find_user_id
    @user = User.find(params[:user_id])
  end
  def card_params
    params.require(:card).permit(:title, :image_url, :desc, :is_shareable) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def create
    @user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end 

  def destroy 
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def showall
    render "showall"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, :require_user

  def index

    @user = User.find(params[:user_id])

    unless @user.first_name
    @user.first_name = @user.name.split(" ")[0]
    @user.last_name = @user.name.split(" ")[1]
    end
    @cards = @user.cards
  end

  def new
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @cards = []
    uniq_image_urls = Card.all.pluck(:image_url).uniq
    
    uniq_image_urls.each do |image_url|
      @cards << Card.find_by_image_url(image_url) 
    end
  end

  def edit
  end

  private

    def check_login
    if session[:user_id] == nil
    redirect_to root_path, notice: "Please log in"
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/emailpreview.html.erb
<nav class="navbar navbar-default colorwhite">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo font" href="#">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
       
      
      
    </ul>
  </div>
</nav>

     <%= stylesheet_link_tag    'pages'%>
<div class="container-fluid">
  <div class="row">
  <!-- <%= @card.image_url %>bhbjb  -->
    <div class="col-sm-6 col-sm-offset-3 box">
      <div class="image" style="background-image: url(<%= @card.image_url %>); background-size: cover; background-position:center;">
        <!--  -->
      </div>
      <div class="cardtext">
        <%= @card.title %>
        <p></p>
        <%= @card.desc %>
        <%= @card.id %>
       
      </div>
    </div>
  </div>
  <br>
  <div class="row text-center">
   
    <!-- <div class="btn btn-default col-sm-2 col-sm-offset-5">Send</div> -->

  </div>
</div>

<div class="navbar navbar-default  navbar-fixed-bottom footer">
<div class="navbar-text "><span class="white">Card created @E_Cards_Designs</span></div>
</div>

app/views/cards/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top color">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo font" href="root_path">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text text font">log in | </li> 
        <li class="navbar-text text"> about us</li>
        <span id="logout"> <%= link_to "Log out", signout_path %>bmbbmb</span>
    </ul>
  </div>
</nav>

<!-- allcards section begins-->

<div class="allcards text-center">
<div class = "row">
<%= link_to "Make my card", new_user_card_path(@user) %>
<div class = 'col-sm-3 rect'></div>
  <div class = 'col-sm-3 rect'><img src="http://cdn.coolmompicks.com/wp-content/uploads/2013/11/ScreenShot2013-07-29at100534AM.png" width ="100%" height = "100%" alt="">
  <br>
  <br>
  <p>
  <span class="cardtitle">by: Sachi</span>&nbsp; &nbsp; &nbsp;
  <span class="likes"> Like <span class="badge">42</span></span>
  </p>
  </div>
  
  <div class = 'col-sm-3 rect'></div>
</div>

<div class = "row">
  <div class = 'col-sm-3 rect'></div><div class = 'col-sm-3 rect'></div><div class = 'col-sm-3 rect'>
    
  </div>
</div>

app/views/cards/new.html.erb
<nav class="navbar  navbar-default colorwhite">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo font" href="#">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text bold"><%= link_to "| Home |", user_path(@current_user) %></li> 
        <li class="navbar-text bold"><%= link_to "| Log out |", signout_path %></li>
      
    </ul>
  </div>
</nav>

<!-- newcard form -->
     <%= stylesheet_link_tag    'pages'%>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 box">
      <div class="image">
       <%= form_for @card,url: user_cards_path, html: {:class => "form-group"} do |f| %>
        <img src="" class="img"  alt="">
       <!--  <div class="Photo" style="background-image: url(<%= @card.image_url %>); background-size: cover; background-position:center;"></div> -->
      </div>
      <div class="cardtext">
          <%= f.text_field :title,:placeholder => "To,",:size => "26x18"  %>
          <p></p>
          <%= f.text_area :desc,:placeholder => "message" ,id: "maintext"%>
          <span><%= f.label "Share my image with other users?" %> 
          <%= f.check_box :is_shareable,class: "checkbox"%></span>
          <p class="text-center" style="display:inline-block;"> 
            <input type="hidden" role="uploadcare-uploader"  data-images-only="" data-image-shrink="300x180 80%" data-public-key="e638bf2c12305f92b0c7" value="<%= @card.image_url %>" name="card[image_url]" class="btn btn-info">
          </p>
      </div>
    </div>
    <div class="controlls col-sm-3"> 
    <!-- Single button -->
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          Background <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="javascript:void(0)"><img src="https://farm3.staticflickr.com/2604/4030150829_168d9461e3_o.jpg" class="smimg" id="backbtn" alt=""></a></li>
          <li><a href="javascript:void(0)"><img src="" class="smimg" id="backwhtbtn" alt=""></a></li>
        </ul>
      </div>
      <p></p>
      <br>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          Font Family  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Happy",root_path, class: "modern" %></li>
          <li><%= link_to "Happy",root_path, class: "cursive" %></li>
        </ul>
      </div>
      <p></p>
      <br>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          Font Color   <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Dark",root_path, class: "dark"%></li>
          <li><%= link_to "Light",root_path, class: "light"%></li>
        </ul>
      </div> 
      <p></p>
      <br>
      <div class="btn-group"> 
            <%= f.submit "Create", class: "btn btn-default btncolor"  %>
          </p>
        <% end %>
      </div> 
    </div> <!-- closing the row -->
  </div>

</div>
<div class="navbar navbar-default  navbar-fixed-bottom footer">
<div class="navbar-text text-center">
<!--  -->
   <img src="https://i.imgur.com/jy1vl2i.png" width="40%" alt="">
   <br>
</div>

<!-- <script type="text/javascript">
  tinyMCE.init({
    selector: '.tinymce',
    // inline: true,
    // fixed_toolbar_container: "#mytoolbar",
    menubar : false,
    resize: "both",
    toolbar: [
        "undo redo | styleselect | bold italic",
        "alignleft aligncenter alignright"
    ]
  });
</script> -->

<script>
  $(document).ready(function(){
    var widget = uploadcare.Widget('[role=uploadcare-uploader]');
    widget.onUploadComplete(function(info) {
      image = info.cdnUrl;
      $(".image").css('background-image', 'url(' + image + ')');
      // $(".img").attr("src", info.cdnUrl);
    });
    <% if @templateCard %>
    $(".image").css('background-image', 'url(<%= @templateCard.image_url %>)');
    <% end  %>
  });
</script>

app/views/cards/sendmail.html.erb
<nav class="navbar navbar-default colorwhite">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo font" href="#">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
       <li class="navbar-text bold"><%= link_to "| Home |", user_path(@current_user) %></li> 
        <li class="navbar-text bold"><%= link_to "| Log out |", signout_path %></li>
      
    </ul>
  </div>
</nav>
<%= stylesheet_link_tag    'pages'%>
<div class="gray">
<br>
  <div class="text-center">
    

              <%= form_tag(email_path(@card)) do %>
                <%= text_field_tag :name, nil,placeholder: "name", class:"form-group" %>
                 <%= text_field_tag :email,nil, placeholder: "email" %>
                <br>
                <%= submit_tag "Send",class: "btn btn-default btncolor" %>
              <% end %>
    
    
  </div>
  <div class="text-center">

  <h3 class="thnk"> Thank you, for choosing E_Cards_design!</h3>
  </div>
  <br>
</div>



<div class="navbar navbar-default  navbar-fixed-bottom footer">
<div class="navbar-text text-center">
  <img src="https://i.imgur.com/y0hRtSk.png" width="40%" alt="">
</div>



 

app/views/cards/show.html.erb
<nav class="navbar navbar-default colorwhite">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo font" href="#">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
       <li class="navbar-text bold"><%= link_to "| Home |", user_path(@current_user) %></li> 
      
      
    </ul>
  </div>
</nav>

     <%= stylesheet_link_tag    'pages'%>
<div class="container-fluid">
  <div class="row">
  <!-- <%= @card.image_url %>bhbjb  -->
    <div class="col-sm-6 col-sm-offset-3 box">
      <div class="image" style="background-image: url(<%= @card.image_url %>); background-size: cover; background-position:center;">
        <!--  -->
      </div>
      <div class="cardtext">
        <%= @card.title %>
        <p></p>
        <%= @card.desc %>
       
      </div>
    </div>
  </div>
  <br>
  <div class="row text-center">
    <%= link_to "send", sendmail_path, :class => "btn btn-warning" %>
    <!-- <div class="btn btn-default col-sm-2 col-sm-offset-5">Send</div> -->

  </div>
</div>


<div class="navbar navbar-default  navbar-fixed-bottom footer">
<div class="navbar-text text-center">
  <img src="https://i.imgur.com/vwzC4fR.png" width="50%" alt="">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecard</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
 
  <link href='https://fonts.googleapis.com/css?family=Poiret+One|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
<script src="https://ucarecdn.com/widget/2.0.5/uploadcare/uploadcare.full.min.js" charset="utf-8"></script>

<script>
  UPLOADCARE_PUBLIC_KEY = "e638bf2c12305f92b0c7";
  UPLOADCARE_LOCALE = "en";
  UPLOADCARE_TABS = "file url facebook gdrive dropbox instagram flickr skydrive";
  // UPLOADCARE_PREVIEW_STEP = true;

</script>
<script>

  uploadcare.openDialog(null, {
      publicKey: "e638bf2c12305f92b0c7",
      imagesOnly: true,
      crop: "300x200",
  });

</script>


</head>
<body class="main">
<% if flash != nil %>
  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <% if key == "notice" %>
        <%= content_tag :div, value, class: "text-center alert alert-warning" %>
      <% elsif key == "alert" %>
        <%= content_tag :div, value, class: "text-center alert alert-danger" %>
      <% else %>
        <%= content_tag :div, value, class: "text-center alert alert-success" %>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= yield %>

</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</html>

app/views/site/index.html.erb
<nav class="navbar color">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo" href="#">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text bold"> | about us |</li>
    </ul>
  </div>
</nav>
<!-- <hr> -->

<div class="container-fluid text-center">
<!-- introduction section begins-->
<div class="introduction">
<br>
<br>
<br>
  <span class="boldtext text-center font1">MAKE IT</span> &nbsp;&nbsp;&nbsp;<span class="boldtext font2">EDIT IT</span>&nbsp;&nbsp;&nbsp; <span class="boldtext font3">SHARE IT</span><br>
  <span class="boldtext text-center font3">LIKE IT</span>&nbsp;&nbsp;&nbsp;<span class="boldtext font1">OWN IT</span>&nbsp;&nbsp;&nbsp;<span class="boldtext font2">SHARE IT</span>
  <span class="boldtext text-center font3">JUST</span>&nbsp;&nbsp;&nbsp;<span class="boldtext font1">TRY</span>&nbsp;&nbsp;&nbsp;<span class="boldtext font2">E_CARDS_DESIGNS!</span>
  <p>
    <p class = "text-center">
   <a href="/auth/facebook" id="login" class="btn btn-primary btn-outline">Login with Facebook</a>
  </p>
 
<!--   <a href="" class="arrowup"><span class="glyphicon glyphicon-chevron-up arrow" aria-hidden="true"></span></a> -->
  </p>
  

</div>
</div>
<!-- introduction section ends-->


<!-- allcards section begins-->
<!-- <div class="allcards text-center">
<div class = "row">
  <div class = 'col-sm-3 rect'><img src="http://cdn.coolmompicks.com/wp-content/uploads/2013/11/ScreenShot2013-07-29at100534AM.png" width ="100%" height = "100%" alt="">
  <br>
  <br>
  <p>
  <span class="cardtitle">by: Sachi</span>&nbsp; &nbsp; &nbsp;
  <span class="likes"> Like <span class="badge">42</span></span>
  </p>
  </div>
  <div class = 'col-sm-3 rect'></div>
  <div class = 'col-sm-3 rect'></div>
</div>

<div class = "row">
  <div class = 'col-sm-3 rect'></div><div class = 'col-sm-3 rect'></div><div class = 'col-sm-3 rect'>
    
  </div>
</div>
 -->


<!-- <nav>
  <ul class="pagination">
    <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
    <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li> <li class="active"><a href="#">2 <span class="sr-only">(current)</span></a></li>
   
  </ul>
</nav> -->

</div>

app/views/site/showall.html.erb
<h1>
all cards here</h1>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<nav class="navbar navbar-default colorwhite">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand logo font" href="#">E_Cards_Designs</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text bold"><%= link_to "| Home |", root_path %></li> 
        <li class="navbar-text bold"><%= link_to "| Log out |", signout_path %></li>
    </ul>
  </div>
</nav>

<script>
UPLOADCARE_PUBLIC_KEY = 'e638bf2c12305f92b0c7';
</script>
<%= stylesheet_link_tag    'pages'%>

  <div class="text-center">
    <span class="head">Would you like to make your own card ?, give it a try.. </span><div class="btn btn-default"><%= link_to "Make my card >", new_user_card_path(@user) %></div>
  </div>
  <div class="allcards text-center"> 
    <div class="col-sm-12">     
        <% @cards.each do |card| %>
          <%# user.cards.each do |card| %>
          <% if card.is_shareable == true %>

            <a href="<%=new_user_card_path(@user)%>?template=<%=card.id%>">
             <div class = 'col-sm-2 rect' ><img src="<%= card.image_url %>"width ="100%" height="100%" alt="">
             </a>
               <div>
                 <!-- <span class="pull-left">by: Sachi</span>&nbsp; &nbsp; &nbsp;
                 <span class="pull-right"> Like <span class="badge">42</span></span> -->
              </div>
            </div>
            
          
          <% end %>
        <% end %>
    </div>
 </div>

  